dist: xenial
matrix:
  include:
    - language: python
      python: "3.6"
      env: TOX_POSARGS="-e py36"
      script:
        - cd cli && tox $TOX_POSARGS
    - language: python
      python: "3.7"
      env: TOX_POSARGS="-e py37"
      script:
        - cd cli && tox $TOX_POSARGS
install:
  - travis_retry pip install tox
